### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by FransHalsjes** [HomeAssistant-Mods/home-assistant-miele-OLD-FORK-DO-NOT-USE#7]
running the miele integration with HA 115 gives:
Logger: homeassistant
Source: helpers/entity.py:438
First occurred: 12:26:14 (7 occurrences)
Last logged: 12:26:44

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/miele/__init__.py", line 148, in refresh_devices
    platform.update_device_state()
  File "/home/homeassistant/.homeassistant/custom_components/miele/sensor.py", line 72, in update_device_state
    device.async_schedule_update_ha_state(True)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 438, in async_schedule_update_ha_state
    assert self.hass is not None
AssertionError

several times per second.

**Comment by kloknibor** [comment]
I am unable to replicate this issue. Do you still have this issue?

**Comment by FransHalsjes** [comment]
Yes, I do. current setup:
![image](https://user-images.githubusercontent.com/70005749/99935161-57ea1100-2d60-11eb-8b8d-8947a3573c75.png)
![image](https://user-images.githubusercontent.com/70005749/99935193-69cbb400-2d60-11eb-990e-7d98aaa0ddb1.png)

**Comment by FransHalsjes** [comment]
I downloaded and installed the latest version of https://github.com/HomeAssistant-Mods/home-assistant-miele .
Restarted HA, and now are getting the error:

![image](https://user-images.githubusercontent.com/70005749/99936627-e0b67c00-2d63-11eb-8624-c0e52a24fd72.png)

**Comment by kloknibor** [comment]
The error you show me is a very old bug. Are you running the latest version of this plugin?

**Comment by kloknibor** [comment]
@FransHalsjes are you using HACS with this plugin? The error you show me is a bug which we has been issue a while back but should be resolved. Also it is just a warning to improve the code. It should still run without an issue... But in my log I don't see any messages like this and i should get them immidiately

**Comment by FransHalsjes** [comment]
I am not using HACS, installed manually. What is the latest version of the plugin? Where can I find it?
 I'l lfetch it from there and retry.

**Comment by kloknibor** [comment]
Just here at the master branch. So basicaly what U already used, just the folder structure you might need to change a little

**Comment by FransHalsjes** [comment]
That is weird! I cloned
https://github.com/HomeAssistant-Mods/home-assistant-miele.git into my HA,
then moved the miele directory to the right place (in /custom_components )
, checked for the logo fix (request #12 is in the __init.py file) and
restarted HA.

Error still is there.

Op ma 23 nov. 2020 om 15:27 schreef Robin Kolk <notifications@github.com>:

**Comment by kloknibor** [comment]
Hmm I might have some time next week to try to replicate your issue by installing it manually... Sorry for the wait though! If you need it rather sooner than later you could try HACS. I basically created this fork for this compatibility after the original dev got unresponsive ;-)!

**Comment by FransHalsjes** [comment]
Thanks for th effort!
To help... I just installed the integration via HACS:
- First removed my manually created old miele directory
- commented the miele login data in configuration.yaml
- Restarted HA
- Cheked if miele was gone. (it was)
- Added https://github.com/HomeAssistant-Mods/home-assistant-miele.git as a repository to HACS
- Restarted HA
- Installed the integration into HA from HACS
- un-commented the miele login data in configuration.yaml
- Restarted HA.

The miele appliances are (again) there, but the errors remain.
Should I have removed the miele_token_cache file as well?

**Comment by kloknibor** [comment]
Hmm thanks for trying, not the result i was hoping for! No the token cache should be ok to not remove... From what I found more plugins had this problem in the past and it has to do with a race condition... Which are hard te reproduce and thus fix... What is our CPU load normally? I'll try to take a look into it next week, sorry I haven't got time earlier

**Comment by kloknibor** [comment]
> I downloaded and installed the latest version of https://github.com/HomeAssistant-Mods/home-assistant-miele .
> Restarted HA, and now are getting the error:
> 
> ![image](https://user-images.githubusercontent.com/70005749/99936627-e0b67c00-2d63-11eb-8624-c0e52a24fd72.png)

just to double check, this is the only issue we have now still?

**Comment by kloknibor** [comment]
and does it still work or not work at all?

**Comment by FransHalsjes** [comment]
It works, can see all my devices. 

I now have 2 issues:

2020-11-25 06:18:32 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for miele doing I/O at custom_components/miele/miele_at_home.py, line 129: self._token = self._session.refresh_token(MieleOAuth.OAUTH_TOKEN_URL,

Occurring at startup of HA

And

2020-11-25 06:19:32 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/miele/__init__.py", line 148, in refresh_devices
platform.update_device_state()
File "/config/custom_components/miele/sensor.py", line 72, in update_device_state
device.async_schedule_update_ha_state(True)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 438, in async_schedule_update_ha_state
assert self.hass is not None
AssertionError

occurring every 5 seconds.

**Comment by kloknibor** [comment]
Hi @FransHalsjes could you try replacing your miele_at_home.py with the following file contents : 

`import json
import logging
import functools

from datetime import timedelta

from requests.exceptions import ConnectionError
from requests_oauthlib import OAuth2Session

_LOGGER = logging.getLogger(__name__)

class MieleClient(object):
    DEVICES_URL = 'https://api.mcs3.miele.com/v1/devices'
    ACTION_URL = 'https://api.mcs3.miele.com/v1/devices/{0}/actions'

    def __init__(self, hass, session):
        self._session = session
        self.hass = hass

    async def _get_devices_raw(self, lang):
        _LOGGER.debug('Requesting Miele device update')
        try:
            func = functools.partial(self._session._session.get, MieleClient.DEVICES_URL, params={'language':lang})
            devices = await self.hass.async_add_executor_job(func)
            if devices.status_code == 401:
                _LOGGER.info('Request unauthorized - attempting token refresh')
                if self._session.refresh_token():
                    return self._get_devices_raw(lang)

            if devices.status_code != 200:
                _LOGGER.debug('Failed to retrieve devices: {}'.format(devices.status_code))
                return None

            return devices.json()

        except ConnectionError as err:
             _LOGGER.error('Failed to retrieve Miele devices: {0}'.format(err))
             return None

    async def get_devices(self, lang='en'):
        home_devices = await self._get_devices_raw(lang)
        if home_devices is None:
            return None

        result = []
        for home_device in home_devices:
            result.append(home_devices[home_device])

        return result

    def get_device(self, device_id, lang='en'):
        devices = self._get_devices_raw(lang)
        if devices is None:
            return None

        if devices is not None:
            return devices[device_id]

        return None

    def action(self, device_id, body):
        _LOGGER.debug('Executing device action for {}'.format(device_id))
        try:
            headers = { 'Content-Type' : 'application/json' }
            result = self._session._session.put(MieleClient.ACTION_URL.format(device_id), data=json.dumps(body), headers=headers)
            if result.status_code == 401:
                _LOGGER.info('Request unauthorized - attempting token refresh')
                if self._session.refresh_token():
                    return self.action(device_id, body)

            if result.status_code == 200:
                return result.json()
            elif result.status_code == 204:
                return None
            else:
                _LOGGER.error('Failed to execute device action for {}: {} {}'.format(device_id, result.status_code, result.json()))
                return None

        except ConnectionError as err:
             _LOGGER.error('Failed to execute device action: {}'.format(err))
             return None


class MieleOAuth(object):
    '''
    Implements Authorization Code Flow for Miele@home implementation.
    '''

    OAUTH_AUTHORIZE_URL = 'https://api.mcs3.miele.com/thirdparty/login'
    OAUTH_TOKEN_URL = 'https://api.mcs3.miele.com/thirdparty/token'

    def __init__(self, client_id, client_secret, redirect_uri, cache_path=None):
        self._client_id = client_id
        self._client_secret = client_secret
        self._cache_path = cache_path

        self._token = self._get_cached_token()

        self._session = OAuth2Session(self._client_id,
            auto_refresh_url=MieleOAuth.OAUTH_TOKEN_URL,
            redirect_uri=redirect_uri,
            token=self._token,
            token_updater=self._save_token)

        if self.authorized:
            self.refresh_token()

    @property
    def authorized(self):
        return self._session.authorized

    @property
    def authorization_url(self):
        return self._session.authorization_url(MieleOAuth.OAUTH_AUTHORIZE_URL, state='login')[0]


    def get_access_token(self, client_code):
        token = self._session.fetch_token(
            MieleOAuth.OAUTH_TOKEN_URL,
            code=client_code,
            include_client_id=True,
            client_secret=self._client_secret)
        self._save_token(token)

        return token

    async def refresh_token(self):
        body = 'client_id={}&client_secret={}&'.format(self._client_id, self._client_secret)
        self._token = await self._session.refresh_token(MieleOAuth.OAUTH_TOKEN_URL,
            body=body,
            refresh_token=self._token['refresh_token'])
        self._save_token(self._token)

    def _get_cached_token(self):
        token = None
        if self._cache_path:
            try:
                f = open(self._cache_path)
                token_info_string = f.read()
                f.close()
                token = json.loads(token_info_string)

            except IOError:
                pass

        return token

    def _save_token(self, token):
        if self._cache_path:
            try:
                f = open(self._cache_path, 'w')
                f.write(json.dumps(token))
                f.close()
            except IOError:
                _LOGGER._warn('Couldn\'t write token cache to {0}'.format(self._cache_path))
                pass
`

and let me know what error you still get?

**Comment by kloknibor** [comment]
import json
import logging
import functools

from datetime import timedelta

from requests.exceptions import ConnectionError
from requests_oauthlib import OAuth2Session

_LOGGER = logging.getLogger(__name__)

class MieleClient(object):
    DEVICES_URL = 'https://api.mcs3.miele.com/v1/devices'
    ACTION_URL = 'https://api.mcs3.miele.com/v1/devices/{0}/actions'

    def __init__(self, hass, session):
        self._session = session
        self.hass = hass

    async def _get_devices_raw(self, lang):
        _LOGGER.debug('Requesting Miele device update')
        try:
            func = functools.partial(self._session._session.get, MieleClient.DEVICES_URL, params={'language':lang})
            devices = await self.hass.async_add_executor_job(func)
            if devices.status_code == 401:
                _LOGGER.info('Request unauthorized - attempting token refresh')
                if self._session.refresh_token():
                    return self._get_devices_raw(lang)

            if devices.status_code != 200:
                _LOGGER.debug('Failed to retrieve devices: {}'.format(devices.status_code))
                return None

            return devices.json()

        except ConnectionError as err:
             _LOGGER.error('Failed to retrieve Miele devices: {0}'.format(err))
             return None

    async def get_devices(self, lang='en'):
        home_devices = await self._get_devices_raw(lang)
        if home_devices is None:
            return None

        result = []
        for home_device in home_devices:
            result.append(home_devices[home_device])

        return result

    def get_device(self, device_id, lang='en'):
        devices = self._get_devices_raw(lang)
        if devices is None:
            return None

        if devices is not None:
            return devices[device_id]

        return None

    def action(self, device_id, body):
        _LOGGER.debug('Executing device action for {}'.format(device_id))
        try:
            headers = { 'Content-Type' : 'application/json' }
            result = self._session._session.put(MieleClient.ACTION_URL.format(device_id), data=json.dumps(body), headers=headers)
            if result.status_code == 401:
                _LOGGER.info('Request unauthorized - attempting token refresh')
                if self._session.refresh_token():
                    return self.action(device_id, body)

            if result.status_code == 200:
                return result.json()
            elif result.status_code == 204:
                return None
            else:
                _LOGGER.error('Failed to execute device action for {}: {} {}'.format(device_id, result.status_code, result.json()))
                return None

        except ConnectionError as err:
             _LOGGER.error('Failed to execute device action: {}'.format(err))
             return None


class MieleOAuth(object):
    '''
    Implements Authorization Code Flow for Miele@home implementation.
    '''

    OAUTH_AUTHORIZE_URL = 'https://api.mcs3.miele.com/thirdparty/login'
    OAUTH_TOKEN_URL = 'https://api.mcs3.miele.com/thirdparty/token'

    def __init__(self, client_id, client_secret, redirect_uri, cache_path=None):
        self._client_id = client_id
        self._client_secret = client_secret
        self._cache_path = cache_path

        self._token = self._get_cached_token()

        self._session = OAuth2Session(self._client_id,
            auto_refresh_url=MieleOAuth.OAUTH_TOKEN_URL,
            redirect_uri=redirect_uri,
            token=self._token,
            token_updater=self._save_token)

        if self.authorized:
            self.refresh_token()

    @property
    def authorized(self):
        return self._session.authorized

    @property
    def authorization_url(self):
        return self._session.authorization_url(MieleOAuth.OAUTH_AUTHORIZE_URL, state='login')[0]


    def get_access_token(self, client_code):
        token = self._session.fetch_token(
            MieleOAuth.OAUTH_TOKEN_URL,
            code=client_code,
            include_client_id=True,
            client_secret=self._client_secret)
        self._save_token(token)

        return token

    async def refresh_token(self):
        body = 'client_id={}&client_secret={}&'.format(self._client_id, self._client_secret)
        self._token = await self._session.refresh_token(MieleOAuth.OAUTH_TOKEN_URL,
            body=body,
            refresh_token=self._token['refresh_token'])
        self._save_token(self._token)

    def _get_cached_token(self):
        token = None
        if self._cache_path:
            try:
                f = open(self._cache_path)
                token_info_string = f.read()
                f.close()
                token = json.loads(token_info_string)

            except IOError:
                pass

        return token

    def _save_token(self, token):
        if self._cache_path:
            try:
                f = open(self._cache_path, 'w')
                f.write(json.dumps(token))
                f.close()
            except IOError:
                _LOGGER._warn('Couldn\'t write token cache to {0}'.format(self._cache_path))
                pass

**Comment by kloknibor** [comment]
@FransHalsjes could you test the dev bracnhe for me and see if that fixes any of the errors? (or brings now ones ;P) dev branch can be found here : https://github.com/HomeAssistant-Mods/home-assistant-miele/tree/dev

**Comment by FransHalsjes** [comment]
got this error...
2020-11-27 08:50:56 ERROR (MainThread) [homeassistant.setup] Error during setup of component miele
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
result = await task
File "/config/custom_components/miele/__init__.py", line 125, in async_setup
client = MieleClient(hass, hass.data[DOMAIN][DATA_OAUTH])
TypeError: __init__() takes 2 positional arguments but 3 were given

(I only installed the modified PY files (miele_at_home.py and sensor.py), took them from the DEV branche

**Comment by kloknibor** [comment]
Was afraid of that... Will give it another shot... Weird thing is it still worked on my test system...

**Comment by kloknibor** [comment]
I think mine keeps working since there remains data from my succesfull setup at some point. I will try an complete new environment for testing and see if I can reproduce it that way :-)

**Comment by FransHalsjes** [comment]
ok! thanks for the swift reply. If I can be of any help.. let me know!

**Comment by kloknibor** [comment]
I just pushed an update for your I/O error. I was able to reproduce this and the solution was actually quite simple. Also my dev branch was based on the original project, so that file was all wrong. Please try again with the files from the master branch and I will try to make this project a standalone fork to not have these issues in the future. 

Although I have been unavailable to reproduce your assertion error in my completely otherwise empty and new test system. Could you see if you still have this error?

**Comment by kloknibor** [comment]
Because of a recent change in the structure of the git repo this repo has been renamed and will be no longer active. When you still require support with your question/issue please open a new issue at : https://github.com/HomeAssistant-Mods/home-assistant-miele

**Comment by FransHalsjes** [comment]
Hi Robin,
Thanks for the work. The IO error is gone.great. However, the assertion
error still is there:

Logger: homeassistant
Source: helpers/entity.py:438
First occurred: 15:19:02 (71 occurrences)
Last logged: 15:24:30
Error doing job: Task exception was never retrieved

Traceback (most recent call last):
  File "/config/custom_components/miele/__init__.py", line 148, in
refresh_devices
    platform.update_device_state()
  File "/config/custom_components/miele/sensor.py", line 72, in
update_device_state
    device.async_schedule_update_ha_state(True)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line
438, in async_schedule_update_ha_state
    assert self.hass is not None
AssertionError



Op za 28 nov. 2020 om 20:22 schreef Robin Kolk <notifications@github.com>:

**Comment by kloknibor** [comment]
Would it be possible to take a look at your set-up under your supervision? Since I'm unable to reproduce this on my test system it makes debugging pretty hard.

**Comment by FransHalsjes** [comment]
Sure! Just tell me what and how

Verstuurd vanaf mijn iPhone

**Comment by kloknibor** [comment]
Ik heb je een mailtje gestuurd ;-)!
